### ISSUE TITLE
Missing challenge_4_data_analysis.ipynb

### ISSUE THREAD

**Issue by 1robroos** [ariannedee/intro-to-python#1]
Hello Arianne,
I think the file `challenge_4_data_analysis.ipynb` is missing from your branch.
It is not really  important, but still ,it is missing :-)

I found a copy at https://github.com/Zeus2k01/Miscellaneous/blob/master/intro-to-python-livelessons-master/Challenges/challenge_4_data_analysis.ipynb

Oh I see a also a `challenge_5_web_app` directory over there. So maybe is that also missing in your branch? I am not there yet with the course :-)

**Comment by ariannedee** [comment]
Hi @1robroos,
This is the wrong repository for that. This one is for the live online training class that is 4 hours long, so covers less content.

All of the code you need for the video is at: [https://github.com/ariannedee/intro-to-python-livelessons](https://github.com/ariannedee/intro-to-python-livelessons)
